# NumPy

In [5]:
import numpy as np

## DataTypes and attribute

In [6]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[10,11,12],[13,14,15],[16,17,18]]])

In [9]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape,a2.shape,a3.shape

((3,), (2, 3), (2, 3, 3))

In [12]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [13]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [14]:
type(a1),type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [16]:
# Create a dataframe from a numpy array 
import pandas as pd
df = pd.DataFrame(a2)

In [17]:
df

0  1  2
0  1  2  3
1  4  5  6

# 2. NumPy Arrays

In [18]:
ones = np.ones((2,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
zeros = np.zeros((2,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
range_a = np.arange(0,10,2)
range_a

array([0, 2, 4, 6, 8])

In [21]:
random_arr = np.random.randint(0,10,size=(3,5))
random_arr

array([[4, 0, 3, 0, 2],
       [8, 5, 3, 6, 4],
       [4, 1, 8, 8, 9]])

In [22]:
random_arr.size

15

In [23]:
random_arr.shape

(3, 5)

In [24]:
random_2 = np.random.random((3,5))

In [25]:
random_2

array([[0.17241117, 0.64154335, 0.5057012 , 0.15432778, 0.21235013],
       [0.44719861, 0.81232702, 0.13352853, 0.03818493, 0.04817478],
       [0.34539122, 0.73004809, 0.98106739, 0.96222831, 0.42121047]])

In [26]:
rand_3 = np.random.rand(3,5)
rand_3

array([[0.57829364, 0.80491533, 0.48981323, 0.65705337, 0.77956555],
       [0.92773692, 0.33840023, 0.57861468, 0.25019351, 0.37802714],
       [0.86218753, 0.30372714, 0.82465523, 0.89366482, 0.55215902]])

In [27]:
# psudo-random numbers
np.random.seed(3)
rand_4 = np.random.randint(10,size = (5,3))
rand_4

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9],
       [9, 5, 7],
       [6, 0, 4]])

In [28]:
rand_4 = np.random.randint(10,size = (5,3))
rand_4

array([[7, 8, 1],
       [6, 2, 2],
       [1, 3, 5],
       [8, 1, 8],
       [7, 8, 1]])

## 3. Viewing arrays and matrices

In [29]:
np.unique(rand_4)

array([1, 2, 3, 5, 6, 7, 8])

In [30]:
a1[0],a2[0]

(1, array([1, 2, 3]))

In [31]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [32]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[0, 5, 4, 1, 5],
         [4, 7, 6, 0, 0],
         [9, 2, 4, 5, 8],
         [8, 7, 5, 1, 1]],

        [[1, 5, 5, 7, 4],
         [3, 0, 0, 0, 0],
         [2, 2, 7, 0, 5],
         [0, 1, 4, 1, 2]],

        [[2, 4, 8, 0, 6],
         [0, 4, 1, 5, 1],
         [8, 8, 7, 0, 0],
         [9, 1, 7, 8, 7]]],


       [[[4, 0, 0, 4, 3],
         [0, 8, 2, 7, 2],
         [1, 3, 2, 4, 1],
         [2, 2, 7, 3, 4]],

        [[1, 6, 7, 9, 1],
         [0, 0, 5, 8, 4],
         [8, 8, 3, 4, 9],
         [2, 5, 4, 7, 9]],

        [[1, 9, 0, 7, 4],
         [8, 8, 4, 1, 4],
         [0, 5, 6, 7, 0],
         [7, 8, 1, 5, 3]]]])

In [33]:
a4[:2,:,:3,:1]

array([[[[0],
         [4],
         [9]],

        [[1],
         [3],
         [2]],

        [[2],
         [0],
         [8]]],


       [[[4],
         [0],
         [1]],

        [[1],
         [0],
         [8]],

        [[1],
         [8],
         [0]]]])

# 4. Manipulating & comparing array

## Arithmatic

In [34]:
a1

array([1, 2, 3])

In [35]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [36]:
a1 + ones

array([2., 3., 4.])

In [37]:
a1 - ones

array([0., 1., 2.])

In [38]:
a1*ones

array([1., 2., 3.])

In [39]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [41]:
a2*a1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [42]:
# how can you reshape a2 to be compatible with a3
# search: "how to reshape numpy arrays"
a3 = a3.reshape(2,3)
a2*a3

ValueError: cannot reshape array of size 18 into shape (2,3)

In [43]:
a2.shape

(2, 3)

In [44]:
a3.shape


(2, 3, 3)

In [45]:
 a1/ones

array([1., 2., 3.])

In [46]:
a2/a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [47]:
a1**2

array([1, 4, 9])

In [48]:
np.square(a1)

array([1, 4, 9])

In [49]:
np.add(a1,a2)

array([[2, 4, 6],
       [5, 7, 9]])

In [50]:
a2%2

array([[1, 0, 1],
       [0, 1, 0]])

In [51]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [52]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Reshaping and Transpose

In [53]:
a2


array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a2.shape

(2, 3)

In [55]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [56]:
a3.shape

(2, 3, 3)

In [57]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [59]:
# reshape() function
a2_r = a2.reshape(2,3,1)
a2_r

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [61]:
a2_r*a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [62]:
# Transpose (T)
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [63]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [64]:
a3.T.shape

(3, 3, 2)

In [65]:
a2.T.shape

(3, 2)

# Dot Product

In [67]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [68]:
# Elementwise multiplication (hadamard product)
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [70]:
# Dot Product
np.dot(mat1,mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot product nut butter sales

In [71]:
np.random.seed(0)
sales_amount = np.random.randint(20,size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [104]:
# creating weekly sales DataFrame
weekly_sales = pd.DataFrame(sales_amount,index=["Mon","Tue","Wed","Thu","Fri"],
                           columns = ["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales.shape

(5, 3)

In [110]:
# Create Prices array
prices = np.array([[10],[8],[12]])
prices

(3, 1)

In [108]:
# Create Butter_prices DataFrame
butter_prices = pd.DataFrame(prices,columns=["Prices"],index=["Almond Butter","Peanut Butter","Cashew Butter"])


butter_rate=butter_prices.T
butter_rate

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [113]:
# Dot product of prices and sales amount
total_sales = prices.T.dot(sales_amount.T)
total_sales

array([[240, 138, 458, 232, 142]])

In [114]:
# Daily sales
daily_sales = butter_rate.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thu  Fri
Prices  240  138  458  232  142

In [117]:
weekly_sales["Total"] = daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total
Mon             12             15              0    240
Tue              3              3              7    138
Wed              9             19             18    458
Thu              4              6             12    232
Fri              1              6              7    142

### Comparision Operators

In [118]:
a1

array([1, 2, 3])

In [119]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
bool_arr = a1 > a2
bool_arr

array([[False, False, False],
       [False, False, False]])

In [123]:
type(bool_arr),bool_arr.dtype

(numpy.ndarray, dtype('bool'))

In [124]:
a1 < 5

array([ True,  True,  True])

In [125]:
a2 > 5

array([[False, False, False],
       [False, False,  True]])

In [126]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [127]:
a2 >2

array([[False, False,  True],
       [ True,  True,  True]])

# 5. Sorting

In [130]:
random_arr

array([[4, 0, 3, 0, 2],
       [8, 5, 3, 6, 4],
       [4, 1, 8, 8, 9]])

In [132]:
random_arr.shape

(3, 5)

In [133]:
np.sort(random_arr)

array([[0, 0, 2, 3, 4],
       [3, 4, 5, 6, 8],
       [1, 4, 8, 8, 9]])

In [135]:
np.argsort(random_arr)

array([[1, 3, 4, 2, 0],
       [2, 4, 1, 3, 0],
       [1, 0, 2, 3, 4]])

In [139]:
np.argmin(random_arr,axis=1)

array([1, 2, 1])

In [138]:
random_arr

array([[4, 0, 3, 0, 2],
       [8, 5, 3, 6, 4],
       [4, 1, 8, 8, 9]])

In [141]:
np.argmax(random_arr,axis=1)

array([0, 0, 4])

# 6. Practice Example

<img src="img/panda.png"/>

In [142]:
# turn image into numbers
from matplotlib.image import imread
panda = imread("img/panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [143]:
panda.shape,panda.size,panda.ndim

((2330, 3500, 3), 24465000, 3)

<img src="img/car-photo.png"/>

In [145]:
car = imread("img/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

<img src="img/dog-photo.png"/>

In [147]:
dog = imread("img/dog-photo.png")
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274